ifndef CONTIKI
  $(error CONTIKI not defined! You must specify where CONTIKI resides!)
endif


CONTIKI_TARGET_DIRS = . dev
CONTIKI_TARGET_MAIN = ${addprefix $(OBJECTDIR)/,contiki-main.o}
CONTIKI_TARGET_SOURCEFILES += platform.c clock.c xmem.c buttons.c labscim_socket.c labscim_linked_list.c labscim_dbg.c labscim_sun_radio.c prop-mode-tx-power.c labscim_sun_50kbps_tsch.c shared_mutex.c

# The different options
MAKE_CFS_POSIX = 1
MAKE_CFS_COFFEE = 2

# Use CFS POSIX the default CFS backend.
MAKE_CFS ?= MAKE_CFS_POSIX

ifeq ($(MAKE_CFS),MAKE_CFS_POSIX)
  CONTIKI_TARGET_SOURCEFILES += cfs-posix.c cfs-posix-dir.c
else ifeq ($(MAKE_CFS),MAKE_CFS_COFFEE)
  MODULES += $(CONTIKI_NG_STORAGE_DIR)/cfs
else
  ${error Invalid MAKE_CFS configuration: "$(MAKE_CFS)"}
endif

# No stack end symbol available, code does not work on 64-bit architectures.
MODULES_SOURCES_EXCLUDES += stack-check.c
# No Serial Peripheral Interface on Native.
MODULES_SOURCES_EXCLUDES += spi.c
# No slip driver on Native.
MODULES_SOURCES_EXCLUDES += slip.c
# No sensor drivers on Native.
MODULES_SOURCES_EXCLUDES += sensors.c



ifeq ($(HOST_OS),Linux)
TARGET_LIBFILES += -lrt
endif

# No stack end symbol available, code does not work on 64-bit architectures.
MODULES_SOURCES_EXCLUDES += stack-check.c
# No Serial Peripheral Interface on Native.
MODULES_SOURCES_EXCLUDES += spi.c
# No slip driver on Native.
MODULES_SOURCES_EXCLUDES += slip.c
# No sensor drivers on Native.
MODULES_SOURCES_EXCLUDES += sensors.c

CFLAGS += -DIS_LABSCIM_CLIENT=1
#CFLAGS += -DLABSCIM_LOG_COMMANDS
CFLAGS += -DLABSCIM_RADIO_SUN=1

CONTIKI_TARGET_SOURCEFILES += tun6-net.c

ifeq ($(HOST_OS),Linux)
TARGET_LIBFILES += -lrt
endif

CONTIKI_SOURCEFILES += $(CONTIKI_TARGET_SOURCEFILES)

# Enable nullmac by default
MAKE_MAC ?= MAKE_MAC_CSMA

### Define the CPU directory
CONTIKI_CPU = $(CONTIKI_NG_RELOC_CPU_DIR)/labscim
include $(CONTIKI_CPU)/Makefile.labscim
